### ISSUE TITLE
[Feature Request] Weekly Newsletter: Include Only Recently Added Content from the Past Week

### ISSUE THREAD

**Issue by jchurchward** [Cloud9Developer/Jellyfin-Newsletter-Plugin#113]
Hello,

Thank you for developing and maintaining the Jellyfin Newsletter Plugin. I find it incredibly useful for keeping users informed about new content. I have a feature request that would enhance its functionality even further.

**Feature Request:**

I would like to request an option to filter and include only the content that has been added in the past week in the newsletter. This feature would allow administrators to send out weekly newsletters that focus on the latest additions to the media library, providing more relevant and timely updates to users.

**Proposed Functionality:**

- Filter by Date Added: An option in the plugin configuration to enable filtering of media items based on the date they were added to the library.
- Time Frame Specification: The ability to specify a time frame (e.g., the past 7 days) for which the newly added content should be included in the newsletter.
- Automatic Scheduling: Support for automatically generating and sending the newsletter on a weekly basis (e.g., every Friday).

**Benefits:**

- Keeps the newsletter content fresh and relevant by focusing on recent additions.
- Helps users stay updated with the latest content without overwhelming them with older items.
- Streamlines the newsletter management process for administrators.

Thank you for considering this feature request. I believe it would greatly enhance the user experience and make the Jellyfin Newsletter Plugin even more valuable.

**Comment by nylimited** [comment]
@jchurchward 

Although I am not the developer I am admittedly confused by your feature request since most, perhaps all, of what you are asking is already available and part of the package ...

**Comment by Cloud9Developer** [comment]
Agreed @nylimited

**Comment by Cloud9Developer** [comment]
```
    Filter by Date Added: An option in the plugin configuration to enable filtering of media items based on the date they were added to the library.
```
Not sure what you mean by this

```
    Time Frame Specification: The ability to specify a time frame (e.g., the past 7 days) for which the newly added content should be included in the newsletter.
```
This is done via the scheduled task

```
    Automatic Scheduling: Support for automatically generating and sending the newsletter on a weekly basis (e.g., every Friday).
```
Again, done via scheduled task

**Comment by jchurchward** [comment]
Thanks, everyone. I'll keep experimenting with it until I get it working, since you've confirmed it's already built in. Cheers.
