### ISSUE TITLE
Issue: Logo does not show when application is installed

### ISSUE THREAD

**Issue by Cloud9Developer** [Cloud9Developer/Jellyfin-Newsletter-Plugin#15]
Logo does not show in Plugins tab after installation

**Comment by Middlepepper** [comment]
I think you need to add a meta.json file that will link to the appropriate logo. I can't find anything else so it might be worth a shot?

here a example from Open subtitles plugin.

`{
    "category": "Metadata",
    "changelog": "### Bug Fixes ###\n- Fix pagination (#92) @MBR-0001\n\n### Tests ###\n- Minor improvements (#90) @Bond-009\n\n### Code or Repo Maintenance ###\n- Use meta ci (#101) @crobibero\n- chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#91) @dependabot\n- Minor improvements (#90) @Bond-009\n- Replace %20 with + in SearchSubtitlesAsync (#89) @MBR-0001\n- Implement Bad Gateway handling & code cleanup (#87) @MBR-0001\n\n### Dependency updates ###\n- chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#91) @dependabot\n\n### CI & build changes ###\n- Use meta ci (#101) @crobibero",
    "description": "Download subtitles from the internet to use with your media files.",
    "guid": "4b9ed42f-5185-48b5-9803-6ff2989014c4",
    "imageUrl": "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png",
    "name": "Open Subtitles",
    "overview": "Download subtitles for your media",
    "owner": "jellyfin",
    "targetAbi": "10.8.0.0",
    "timestamp": "2022-03-28T00:04:24Z",
    "version": "18.0.0.0"
}`

**Comment by Middlepepper** [comment]
Actually Correction look like you just need to set it in the Build.yaml

`imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png"`

From look at this commit.
https://github.com/jellyfin/jellyfin-plugin-opensubtitles/commit/6ceff9adc7d08ef47930699a94031f734d890062

**Comment by TheDMV2** [comment]
The issue is in the path.
When first installed: .../Plugins/60f478ab2dd64ea0af1004d033f75979/0.6.0/Image
Then you restart the server to activate the plugin, and the path changes to: ...//Plugins/60f478ab2dd64ea0af1004d033f75979/0.6.0.0/Image

0.6.0 vs 0.6.0.0

I think all Jellyfin version numbers have to be in 4 parts, while you are using 3.

**Comment by Cloud9Developer** [comment]
Resolved as of version 0.6.2.0
