### ISSUE TITLE
Error _ not working for me at all

### ISSUE THREAD

**Issue by roy2810** [Cloud9Developer/Jellyfin-Newsletter-Plugin#18]
Running on Debian 11
Jellyfin Version 10.8.9
Below are the logs, not sure what else to look at?

[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Setting Config Paths: 
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] 
  DataPath: /var/lib/jellyfin/data
  TempDirectory: /var/cache/jellyfin/temp
  PluginsPath: /var/lib/jellyfin/plugins
  MyDataDir: /var/cache/jellyfin/temp/Newsletters/
  NewsletterDir: /var/cache/jellyfin/temp/Newsletters/myNewsletters/
  ProgramDataPath: /var/lib/jellyfin
  ProgramSystemPath: /usr/lib/jellyfin/bin/
  SystemConfigurationFilePath: /etc/jellyfin/system.xml
  LogDirectoryPath: /var/log/jellyfin
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Gathering Data...
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Opening Database: /var/lib/jellyfin/data/newsletters.db
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Creating Tables...
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Executing SQL Statement: create table if not exists CurrRunData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Executing SQL Statement: create table if not exists CurrNewsletterData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Executing SQL Statement: create table if not exists ArchiveData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Done Init of tables
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Running Query: SELECT * FROM ArchiveData;
[NLP]: [2023-03-17] :: [08:07:09] - [INFO] Returning ArchObj
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Scan Size: 328290
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Series: True Blood
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Season: Specials
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Episode Name: Jessica's Blog - The Worst Spa Night Ever
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Episode Number: 31
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Series Overview: Telepathic waitress Sookie Stackhouse encounters a strange new supernatural world when she meets the mysterious Bill Compton, a southern Louisiana gentleman and vampire.
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] ImageInfos: /var/lib/jellyfin/metadata/library/6f/6fa286e95c74f2640e13f02869204ed4/poster.jpg
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] 6fa286e95c74f2640e13f02869204ed4
[NLP]: [2023-03-17] :: [08:07:21] - [ERR] An error has occured: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Jellyfin.Plugin.Newsletters.Scripts.SCRAPER.Scraper.BuildJsonObjsToCurrScanfile()
   at Jellyfin.Plugin.Newsletters.Scripts.SCRAPER.Scraper.GetSeriesData()
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Closing Database: /var/lib/jellyfin/data/newsletters.db
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Opening Database: /var/lib/jellyfin/data/newsletters.db
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Creating Tables...
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Executing SQL Statement: create table if not exists CurrRunData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Executing SQL Statement: create table if not exists CurrNewsletterData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Executing SQL Statement: create table if not exists ArchiveData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,PRIMARY KEY (Filename));
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Done Init of tables
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Running Query: SELECT COUNT(*) FROM CurrNewsletterData;
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Closing Database: /var/lib/jellyfin/data/newsletters.db
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] There is no Newsletter data.. Have I scanned or sent out a newsletter recently recently?
[NLP]: [2023-03-17] :: [08:07:22] - [INFO] Database lock file does not exist. Database is not use: /var/lib/jellyfin/data/newsletters.db.lock

**Comment by Cloud9Developer** [comment]
I have another user with an issue as well. I THINK it's due to the filename format (spaces and special characters). I plan on looking into it today. If I can reproduce and get it fixed, I'll upload a patch (V0.3.2)

**Comment by Cloud9Developer** [comment]
Can you provide your full filepath for that episode (listed below)? Primarily looking for your media directory setup so I can replicate

[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Series: True Blood
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Season: Specials
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Episode Name: Jessica's Blog - The Worst Spa Night Ever
[NLP]: [2023-03-17] :: [08:07:21] - [INFO] Episode Number: 31

**Comment by Cloud9Developer** [comment]
At closer inspection, it's failing to get your episode's Physical File path. 

In addition to the above information I asked for, what's your setup? Is your media local to your Jellyfin install?

**Comment by roy2810** [comment]
its a mounted gdrive using rclone.  Below are the mounted drives.

root@media:/mnt/tv# ls
 Documentaries   RequestsTV           'Series - 2015-2019'
 Excercise      'Series - 0000-1999'  'Series - 2020-2024'
 Fishing        'Series - 2000-2009'  'System Volume Information'
 RequestsAnime  'Series - 2010-2014'

**Comment by roy2810** [comment]
![image](https://user-images.githubusercontent.com/24738145/225974985-afd79391-742c-45e6-9498-29acdc0ccd5b.png)

**Comment by Cloud9Developer** [comment]
Alright, thanks! What about the full path to 'Jessica's Blog - The Worst Spa Night Ever' (True Blood) (Special) (Episode 31)?

I.e. /mnt/tv/Documentaries/TrueBlood/Specials/Ep31.mkv

**Comment by roy2810** [comment]
Thats odd, I can not find that epeisode

**Comment by Cloud9Developer** [comment]
That's probably the issue then. On jellyfin, re-scan your library, then run the scheduled task "Optimize database"

After that, try running the plugin again and see if you get the same error

**Comment by roy2810** [comment]
will give it a go.  looked at my history, I have never downloaded that episode.  Would this stop the entire plugin working though?

**Comment by Cloud9Developer** [comment]
Yes, becuase I use the filename/filepath as a primary key in the Newsletter database. If it exists in Jellyfin, it should have a file associated with it, and it'll be unique for EVERY item in your library.

I MAY be able to git it to skip said item if it errors out, but I'll need to re-org some logic. 
That, and I don't know how to test if it's working properly (skipping your error) after the change since I'm not sure how to replicate not having a file name attached

**Comment by roy2810** [comment]
i am happy to test anything as needed, I work from home so normally about

**Comment by Cloud9Developer** [comment]
Alright, in that case, are you able to build .net apps (dotnet cli)?

**Comment by roy2810** [comment]
no sorry I do not know how

**Comment by Cloud9Developer** [comment]
No worries, I'm actually just made the change and am about to test if it still works as expected on my end. If it does, I'll publish a new release, so you can update your plugin that way. Give me a bit

**Comment by Cloud9Developer** [comment]
Alright, v3.0.2 has been released. Install that new version and let me know

**Comment by roy2810** [comment]
okay so i have received a newsletter but nothing in it other than the heading

![image](https://user-images.githubusercontent.com/24738145/225986404-17699873-f9aa-4bb4-a52f-71649987a213.png)

**Comment by Cloud9Developer** [comment]
Can you share your log file for the plugin?

**Comment by roy2810** [comment]
[Log.txt](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/files/11004880/Log.txt)

**Comment by Cloud9Developer** [comment]
Alright lets try this:
Do you know where your jellyfin config folder is? I need you to locate that, then inside of the "Jellyfin Newsletters_0.3.2" directory, extract and replace the .dll file with the one I'm about to share

delete the file /var/lib/jellyfin/data/newsletters.db (since it looks like newsletter data was moved to archive)

Then restart jellyfin


 
[nl-test.zip](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/files/11005167/nl-test.zip)

**Comment by roy2810** [comment]
looks great, email received with data

**Comment by Cloud9Developer** [comment]
Perfect! I'll update that in the current release
