### ISSUE TITLE
No poster images in the email

### ISSUE THREAD

**Issue by ZsiGiT** [Cloud9Developer/Jellyfin-Newsletter-Plugin#25]
Hi dev!

This plugin works fine, exept there are no image in email:

log:
[NLP]: [2023-03-18] :: [18:22:03] - [ERR] Encountered an error parsing Season Number for: /mnt/18TBRAID5/HDfilmek/Jégvarázs 2. (2019)/Jégvarázs 2. (2019).mkv
[NLP]: [2023-03-18] :: [18:22:03] - [ERR] System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s, IFormatProvider provider)
   at Jellyfin.Plugin.Newsletters.Scripts.SCRAPER.Scraper.BuildObjs(List`1 items, String type)

The movie is "Frozen 2" , and the hungarian name: "Jégvarázs 2." Name and every meta info ( images, plot etc.) are from tmdb. Scraper: Tinymediamanager

When open in next window the empty image in email, the error is: 

404. That’s an error.

The requested URL /proxy/****************************************=s0-d-e1-ft was not found on this server. That’s all we know.

URL: https://ci4.googleusercontent.com/proxy/**************************************=s0-d-e1-ft#http://403

![email](https://user-images.githubusercontent.com/47332170/226133696-bffea228-e2e3-467b-bf3d-d1122efbcbb3.jpg)

![structure](https://user-images.githubusercontent.com/47332170/226133700-81cf3ef2-7263-4b65-b854-81e86123a765.jpg)

**Comment by ZsiGiT** [comment]
Edit:

This method working fine:  

http://siberiancmscustomization.blogspot.com/2020/10/how-to-get-imgur-client-id.html

Please close this issue!!

Thanks

**Comment by Cloud9Developer** [comment]
Closing due to use fix
