### ISSUE TITLE
Request for max log size

### ISSUE THREAD

**Issue by roy2810** [Cloud9Developer/Jellyfin-Newsletter-Plugin#26]
I managed to fill my hard drive with the newsletter logs, oops.

**Comment by Cloud9Developer** [comment]
This is already taken care of by base jellyfin actually. Just make sure your scheduled task "Clean Log Directory" is enabled to run every so often and don't keep Debug mode turned on for this plugin.

However, if you don't have debug mode turned on and it's filling up your harddrive, let me know! Will need to check what's being logged and update some of that :)
