### ISSUE TITLE
Plugin all of a sudden not sending email

### ISSUE THREAD

**Issue by pine-serpent** [Cloud9Developer/Jellyfin-Newsletter-Plugin#29]
I love this plugin and it worked for about 3 days after i set it up.  However after those first 3 days i no longer get an email anymore.  I did no change anything but it just stopped.  i continue to have new media added to both the tv and movie libraries.

any thoughts why it would just stop all of a sudden?  thank you.

**Comment by Cloud9Developer** [comment]
Hmm, it's set to send out mail once a week by default (unless you changed the frequency in your scheduled task).

Could you share your logs for the plugin?

**Comment by pine-serpent** [comment]
I have mine to send everyday early in the morning. for the first few days it emailed but then stopped.

where is the logs for this plugin?

**Comment by Cloud9Developer** [comment]
You can see logs for the plugin on your administration dashboard in jellyfin

**Comment by pine-serpent** [comment]
I just tried it again and now it worked. not sure what changed. I appreciate the assistance.
