### ISSUE TITLE
Is it possible to send the newsletter everytime i click the scheduled task button?

### ISSUE THREAD

**Issue by Gaffers2277** [Cloud9Developer/Jellyfin-Newsletter-Plugin#40]
Im testing this plugin and want to be able to send the news letter everytime i change things. I thought this was what debug mode did but doesn't seem like it. Im having the same issue as #34 and deleting the database each time takes like 4 hours to rebuild. Am i missing something or is this just how it is for now?

**Comment by Cloud9Developer** [comment]
Debug mode just adds additional logging to the log file.

You can manually modify and delete items from the newsletters.db file. That will require you to have a sqlite database program and run some SQL queries to search for the items you want to delete and run the delete query.

**Comment by Gaffers2277** [comment]
Okay cool, I have DBbrowser and can edit it. I think i have it all working now. Its a great plugin! Looking forward to newer versions when you get time
