### ISSUE TITLE
Plugin's logo doesnt appear

### ISSUE THREAD

**Issue by FrankJeager** [Cloud9Developer/Jellyfin-Newsletter-Plugin#41]
A screenshot is better than any explanatrion :

![snapshot1](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/106985437/37ea78d5-6b50-4d8a-95e9-9efd89d949f0)

But I don't understand why...

**Comment by Cloud9Developer** [comment]
Yep, known issue. SHOULD be fixed in the next release (if I can ever find time to work on it lol).

**Comment by TheDMV2** [comment]
Not fixed in 0.6.0, because it should be version 0.6.0.0, so the path is wrong. Easy fix :)
