### ISSUE TITLE
IndexOutOfRangeException in logs

### ISSUE THREAD

**Issue by FrankJeager** [Cloud9Developer/Jellyfin-Newsletter-Plugin#42]
I have a lot (more than 52 000) IndexOutOfRangeException in the logs.

Example :

[NLP]: [2023-05-22] :: [21:54:18] - [ERR] Error processing your file..
[NLP]: [2023-05-22] :: [21:54:18] - [ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Jellyfin.Plugin.Newsletters.Scripts.SCRAPER.Scraper.BuildObjs(List`1 items, String type)

**Comment by FrankJeager** [comment]
It seems Jellyfin is creating "virtual" episodes without a real file attached to it.
Maybe some tests must be put here to filter those.

**Comment by Cloud9Developer** [comment]
I'm just seeing this. You are right, that's the cause of it. I THINK I resolved it as part of the last release (I was seeing those as well and filling up logs lol)
