### ISSUE TITLE
Having issues with Local JF Hosting of images, not loading in News Letter.

### ISSUE THREAD

**Issue by Gaffers2277** [Cloud9Developer/Jellyfin-Newsletter-Plugin#43]
I have installed the Plugin and its really nice, but the images don't load in the emails. I think it might be the same issue as #34. I get the same Google error when opening the image link. The images seem to be broken in the email.

I have tried to delete the newletter.db but it still happens, i also added the WAF rule to Cloudflare but still nothing. I have Jellyfin publicly accessible through a Nginx Reverse Proxy instead of port forwarding and use Cloudflare to proxy and for security. 

As i said i added the rule to WAF in Cloudflare. My Scraper Config is https://jellyfin.DomainName.com

I assume i don't need to add the port number at the end as its going through the reverse proxy which points to the Server IP and Port in Nginx. I can confirm the rest of the SMTP stuff works so it seems to be just the images. 

For reference im using jellyfin Server 10.8.10 on Windows 10

**Comment by Cloud9Developer** [comment]
It has to do with your networking/firewall setup. You've tried adding this rule in your Cloudfare WAF: https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/issues/34#issuecomment-1513798274
?

**Comment by Gaffers2277** [comment]
Yeah, i added that rule to Cloudflare WAF

**Comment by Gaffers2277** [comment]
I get the same error from google as https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/issues/34#issuecomment-1504871430 from #34

**Comment by Cloud9Developer** [comment]
> But if i just use https://jellyfin.DomainName.com/Items/d88c67bf92c5346388ee651ddbb1ff68/Images/Primary it opens the image

Yep, than something is still blocking the traffic in your WAF in cloudflare. Look at the traffic to see what that is, then you'll need to add that as a rule to allow the traffic

**Comment by Gaffers2277** [comment]
Ahh okay, sorry im kinda new to Cloudflare. Where do i need to look for the traffic??

**Comment by Cloud9Developer** [comment]
I'm not sure myself to be honest, since I don't use cloudflare 😅

**Comment by Gaffers2277** [comment]
Could i be that i have the rule under a block all contries other then the UK?

**Comment by Gaffers2277** [comment]
It is the Country rule is blocking google and specifically says the .com/Items/ bit haha

**Comment by Cloud9Developer** [comment]
Closing this since I'm assuming it's resolved. If not, let me know :)
