### ISSUE TITLE
Test button greyed out. 

### ISSUE THREAD

**Issue by MakD** [Cloud9Developer/Jellyfin-Newsletter-Plugin#45]
The button to test the SMTP config is greyed out even after entering details. Unable to check, proceeded with manually triggering both the task, but no mails yet.

**Comment by Cloud9Developer** [comment]
The button color is grey and doesn't change. If you aren't getting emails, the config isn't correct. What's your email provider? Gmail?

**Comment by MakD** [comment]
Yes. Using the defaults just added my mail id and password

**Comment by Cloud9Developer** [comment]
Are you using your normal password? If so, that's your issue since Gmail requires an application password for 3rd party apps. Give me a sec and I'll tell you where to go to generate one

**Comment by Cloud9Developer** [comment]
Google Account Settings > Security > 2-Step Verification (turned on) > App Passwords

**Comment by MakD** [comment]
Ohh. I just created a custom app password, replaced saved and tested. Don't seem to get the test mail yet

**Comment by MakD** [comment]
Or do I need another mail password. If so what needs to be the device? Custom?

**Comment by Cloud9Developer** [comment]
You just need yourgmail@gmail.com, app_password from the location I gave above, port 587, and server smtp.gmail.com

**Comment by MakD** [comment]
@Cloud9Developer error log below

[NLP]: [2023-07-25] :: [02:09:26] - [ERR] An error has occured: System.Net.Mail.SmtpException: Failure sending mail.
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:74.125.24.109]:587
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Jellyfin.Plugin.Newsletters.Emails.EMAIL.Smtp.SendTestMail()

**Comment by MakD** [comment]
Damn firewall port issue. Solved and good to go

**Comment by JulianOestreich90** [comment]
@MakD Can i ask what was your exact port issue? I use jellyfin in a docker container and have the same issue
