### ISSUE TITLE
[Feature Request] Entry information able to add as extra tags

### ISSUE THREAD

**Issue by TheDMV2** [Cloud9Developer/Jellyfin-Newsletter-Plugin#60]
Feature request: Able to pull in item information as extra tags. Such as:

1) A {score} type code to insert the IMDB/Rotten Tomatoes ratings, pulled from the local DB.
2) {year} for year released
3) {rating} for rating
4) {duration} for duration (n/a for multiple tv episodes, only singles and movies)
5) {genres} for genres

![image](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/102610497/8be0f40e-3bfa-4d93-a02c-2e49eaa2b47f)

**Comment by Cloud9Developer** [comment]
This will be coming in a future update soon-ish! Sorry it's taken me a bit, but work is finally slowing down :)

**Comment by Cloud9Developer** [comment]
Available in v0.6.4.2!
