### ISSUE TITLE
Diagnostic-Code: smtp; 554 5.7.1 Spam message rejected

### ISSUE THREAD

**Issue by pine-serpent** [Cloud9Developer/Jellyfin-Newsletter-Plugin#71]
starting just a couple days ago I am receiving undelivered return to sender email error.

Reporting-MTA: dns; smtp1.xxx.org
X-Postfix-Queue-ID: EB5ED1398
X-Postfix-Sender: rfc822; xxxx@xxx.org
Arrival-Date: Wed, 24 Jan 2024 14:00:03 +0100 (CET)
Final-Recipient: rfc822; xxxx@xxx.com
Original-Recipient: rfc822;xxxx@xxx.com
Action: failed
Status: 5.7.1
Remote-MTA: dns; mout-p-201.xxx.org
Diagnostic-Code: smtp; 554 5.7.1 Spam message rejected

when I use the test button in the email it works and is delivered.
also when I manually send an email from my email to the destination email it works.

thanks for any help in advance.

**Comment by Cloud9Developer** [comment]
My best guess is whatever email address you're sending it to is marking the newsletter as spam and rejecting it immediately. I imagine there would be a setting on said email host somewhere to allow/whitelist the newsletter, but that would be out of my hands
