### ISSUE TITLE
Newsletter output malformed for Shows

### ISSUE THREAD

**Issue by solidsnake1298** [Cloud9Developer/Jellyfin-Newsletter-Plugin#76]
The format/output for shows is malformed.  Movies are formatted correctly.

![image](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/137357145/3daffe54-0116-434f-97be-1a70698e121a)

![image](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/137357145/7996cd13-a43f-49c3-b84e-37025300b78a)

I have not been able to get a single show to display correctly.

It also treats whole libraries like a show.

![image](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/137357145/b7177219-1d31-4956-a474-34ded32c8dd6)

Movies always work correctly.

![image](https://github.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/assets/137357145/dbf68df3-97e1-4f9e-b2d1-b0b8870f2ec1)

**Comment by solidsnake1298** [comment]
An example entry from the DB.

`/media/library/TV Shows/Adventure Time/S02e25.mkv|TV Shows|-1|25||https://jellyfin.domain.tld:50443/Items/24178277f1a179c637ce237a0d3834e4/Images/Primary|24178277f1a179c637ce237a0d3834e4|/var/lib/jellyfin/metadata/library/02/02953f7f18c1d6ddffc2a8d00cc275aa/poster.jpg|Series`

**Comment by Cloud9Developer** [comment]
Still in my backlog, bare with me :) I'm starting to get some free time now. I'm planning on doing a pretty large overhaul of how the plugin works honestly, so that may address this issue

**Comment by Cloud9Developer** [comment]
After some major code refactoring, I scanned my ENTIRE library (3900 items total), No issues with formatting! So hopefully once I push the release, you shouldn't have this issue anymore :)

**Comment by TheDMV2** [comment]
>It also treats whole libraries like a show.

It is still doing this for me as well (even after deleting my db yesterday). v0.6.4.2

**Comment by Cloud9Developer** [comment]
I believe we discovered why in matrix the other night. It has to do with not following the proper file structure. @solidsnake1298 can you confirm if your re-org worked?

**Comment by solidsnake1298** [comment]
It did.

**Comment by solidsnake1298** [comment]
Specifically, I did not have season folders for each season of a show.

**Comment by Cloud9Developer** [comment]
Pinned this for others, thanks for confirming!
