### ISSUE TITLE
[BUG REPORT] Time zone not honored

### ISSUE THREAD

**Issue by nylimited** [Cloud9Developer/Jellyfin-Newsletter-Plugin#82]
I am running Jellyfin and the plugin on an Asustor NAS in a Docker container. In addition to missing images (I already reported) it seems the plugin does not know or honor local time zone. I am in the US Eastern time zone and scheduled the plugin (not the scraper) to run once a week at 17:00h. The newsletter was emailed at 12:00h. Since I wanted to email at 17:00h I changed the schedule time to 22:00h which ..  you guessed it ..  promptly emailed the newsletter at 17:00h Eastern US time.  I doubt this has any impact on the missing images previously reported. 

Checking the newsletter logs you can see a run which took place around 19:13h local time showing that the newsletter thinks the time is after midnight:

`[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Setting Config Paths: 
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] 
  DataPath: /config/data
  TempDirectory: /cache/temp
  PluginsPath: /config/plugins
  MyDataDir: /cache/temp/Newsletters/
  NewsletterDir: /cache/temp/Newsletters/myNewsletters/
  ProgramDataPath: /config
  ProgramSystemPath: /jellyfin/
  SystemConfigurationFilePath: /config/config/system.xml
  LogDirectoryPath: /config/log
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Gathering Data...
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Opening Database: /config/data/newsletters.db
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Creating Tables...
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Executing SQL Statement: create table if not exists CurrRunData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,Type TEXT,PRIMARY KEY (Filename));
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Alter Table no longer required as of V0.5.1!
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Executing SQL Statement: create table if not exists CurrNewsletterData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,Type TEXT,PRIMARY KEY (Filename));
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Alter Table no longer required as of V0.5.1!
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Executing SQL Statement: create table if not exists ArchiveData (Filename TEXT NOT NULL,Title TEXT,Season INT,Episode INT,SeriesOverview TEXT,ImageURL TEXT,ItemID TEXT,PosterPath TEXT,Type TEXT,PRIMARY KEY (Filename));
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Alter Table no longer required as of V0.5.1!
[NLP]: [2024-03-02] :: [00:13:18] - [INFO] Done Init of tables
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Parsing Series..
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Series Scan Size: 7047
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Series: M*A*S*H
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Season: Season 2
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Episode Name: For Want of a Boot
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Episode Number: 17
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Series Overview: The 4077th Mobile Army Surgical Hospital is stuck in the middle of the Korean war. With little help from the circumstances they find themselves in, they are forced to make their own fun. Fond of practical jokes and revenge, the doctors, nurses, administrators, and soldiers often find ways of making wartime life bearable.
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] ImageInfos: /config/metadata/library/1b/1bc8415c9c8af5f28a84e04e362846b0/poster.jpg
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] 1bc8415c9c8af5f28a84e04e362846b0
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] /sharefolder/PLEX_DATA/COMMON/TV/Mash/Season 02/Mash - S02E17 - For Want Of A Boot.mp4
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] ---------------
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Running Query: SELECT COUNT(*) FROM CurrRunData WHERE Filename='/sharefolder/PLEX_DATA/COMMON/TV/Mash/Season 02/Mash - S02E17 - For Want Of A Boot.mp4';
[NLP]: [2024-03-02] :: [00:13:19] - [INFO] Running Query: SELECT COUNT(*) FROM CurrNewsletterData WHERE Filename='/sharefolder/PLEX_DATA/COMMON/TV/Mash/Season 02/Mash - S02E17 - For Want Of A Boot.mp4';`

**Comment by Cloud9Developer** [comment]
I checked on my end (running docker as well), timezone is honored. Are you sure you have your TZ configured correctly in the container? (need to set the TZ in your compose/docker run command)

**Comment by nylimited** [comment]
> I checked on my end (running docker as well), timezone is honored. Are you sure you have your TZ configured correctly in the container? (need to set the TZ in your compose/docker run command)

I am old enough to know all about "assume" but ..   no, TZ variable was not defined but I assumed it was since the Jellyfin container reported the correct time.  My bad - fixed. 

Will retest when I have some new media added.  Apologies for the false alarm!

**Comment by Cloud9Developer** [comment]
No worries! It may be that jellyfin does something to get your local timezone somehow. Not sure how they do it (if they do it), but let me know if setting it works!

**Comment by nylimited** [comment]
Sorry, I updated my previous post (2 up) before realizing you already read it ...  moving the edited text here for you:


Added a new movie and modified the schedules for scraper and newsletter. All worked on correct time! However, the newsletter that was generated is still rejected by GMX.COM

Looking at the new log I see a lot of errors and warnings listed. It seems like the plugin is going through ALL the shows and movies again although only one needed to be shown and reported on. The generated newsletter contained only the 1 recent update.

There seems to be no data recorded in the log about the sending process or email headers generated.

**Comment by Cloud9Developer** [comment]
Yeah, it still scans the entire library, but it skips processing items it already found (probably can clean that up in a later update LoL) 

As for no logs for the sending process, I'll have to check. There should be some logs there since it's parsing and building out the newsletter, but I'll have to double check that. Think I responded to the other issue about GMX (could be BCC instead of TO?)

**Comment by nylimited** [comment]
Understood on the scans.  Not an issue for me.  It can be a bit of a problem for you if you wish to look through logs, of course.  If you want to scan the last log - which produced only one item for the newsletter - you will have to look through more than 115000 lines of text. 

As for the BCC vs TO ..  interesting question.  I always thought everyone was sending multiple addresses via BCC but prhaps Ombi sends individual emails?  Ouch!  Still, all the BCCs get through except GMX so something is different. It is, at best, difficult to capture every facet of an outgoing email. I'll have to try and dig up some more info somewhere.

**Comment by Cloud9Developer** [comment]
Yeah, I agree with that lol. Logging can use some more fine tuning. I'll see about that for the next update
