### ISSUE TITLE
Buh bye ...

### ISSUE THREAD

**Issue by nylimited** [Cloud9Developer/Jellyfin-Newsletter-Plugin#84]
I have too many issues with this plugin and none of my reports have ever been answered - time to move on. If the plugin is working for you by all means keep using it.  If not, take a look at Ombi's newsletter.

So long, everyone!

**Comment by Cloud9Developer** [comment]
I've made note of your reports, but life has been busy and I have had no time to sit down and work on the plugin. Should have some time coming up soon when my current project for work ends, so should be able to start doing some major updates. 

Sorry you've felt ignored here, promise I see every report though
