### ISSUE TITLE
Newsletter always containing my full library and not only the new added movies

### ISSUE THREAD

**Issue by potof411** [Cloud9Developer/Jellyfin-Newsletter-Plugin#86]
Hello, 
First thanks for your work ^^!
I managed to make it work on my dockerred jellyfin (hosted on a synology) but for any reason each week the newsletter sent contains my full library instead of just listing the movies added from the previous newsletter...
Any Idea of the reason ?
Thanks for any help

**Comment by Cloud9Developer** [comment]
It list the same media every week? Are the file names constantly changing ? If so, that'd be why.

**Comment by potof411** [comment]
The files are not changing neither name nor folder, it just lists them all every week...(adding the new ones at the bottom of the newsletter ...which is huuuuge ^^)
BTW thanks for your very quick answer :)

**Comment by Cloud9Developer** [comment]
Odd.. I plan on doing some major updates pretty soon. Code clean up, feature additions, etc (also prep for Jellyfin 10.9.0 to be released) so maybe whatever is causing this issue will get fixed when I'm able to get around to that.

Work's been keeping me busy this past year so I haven't had much time/drive to sit down and work on this project, sadly.. I apologize but do hope you bear with me :)

**Comment by Cloud9Developer** [comment]
I'm getting around to doing some updates finally! Are you still having this issue? and if so, could you share your logs with me? (preferably with debug turned on and attempt to run scan AND email back to back via the scheduled tasks)

**Comment by potof411** [comment]
hey, yes, still having the issue :(
I'm in a hurry because I'm just leaving for a long week end, so just fetched the current log I already have and uploaded it thru we transfer (more than 50Mo file)
Here is the link : 
https://we.tl/t-n9GdGwOG0V
Let me know if it's right for you, I can redo one on my retrun next week
Thanks for your time !

**Comment by Cloud9Developer** [comment]
I'm going through the logs now, it looks to be processing perfectly fine. That said, I don't see anywhere in the logs in which you are sending out emails. (I assume you haven't because of this issue).

Can you send out a newsletter (If only to yourself) so that I can see what's going on there in the logs? Can run the scheduled task manually to send out the email

**Comment by potof411** [comment]
Hello, I'm not sure to understand... I'm actually already sending (and recieving) properly the newsletter to my gmail adress.
The only issue is that it contains each time the full list of my medias instead of containing only the new medias added from previous newsletter.

**Comment by Cloud9Developer** [comment]
Understood. That said, I need to see logs (debug logs) from right after the email gets sent so I can see what it's doing with the database calls.

The logs you shared (expired now, can't access the link anymore) didn't have the email task logs, only the scan logs

**Comment by potof411** [comment]
Hey 
I'm sorry for not having given any news... Just to let you know that I finally solved the issue today !!!
The reason was that my librairies db failed to achieve refreshing because of this env variable : 
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT set to 1 (if I understand it is somehow related to dealing with special characters or not and because I'm french I have several medias with special letters like "ç")
I rebuilt the docker container switching it to 0, forced refresh the librairies (which sucessfully ended) and what a surprise, the newsletter I recieved thanks to your plugin just contained the recently added medias ^^
Thanks again for your work !
I think we can consider this issue as solved...
