### ISSUE TITLE
Jellyfin 10.9 broke Newsletter Plugin?

### ISSUE THREAD

**Issue by pine-serpent** [Cloud9Developer/Jellyfin-Newsletter-Plugin#90]
i think Jellyfin 10.9 broke this plugin.   I am getting failed for both tasks "Email Newsletter" and "filesystem scraper."

i have not changed anything and it worked until i updated jellyfin.  let me know what other info might be helpful, i am new to this.  thank you!

**Comment by Cloud9Developer** [comment]
I just updated jellyfin for 10.9 (as of yesterday I think?). The latest version (0.6.2.0) should work now, let me know if you have issues

**Comment by Cloud9Developer** [comment]
Duplicate of #91 , issue should be resolved with latest release
