### ISSUE TITLE
wizarr new user support

### ISSUE THREAD

**Issue by binarygeek119** [Cloud9Developer/Jellyfin-Newsletter-Plugin#95]
i use wizarr to add new users to jellyfin. wizarr says they wont support plugins, but said it could be done with there api and jellyfin api. i just dont now how to do it. what i would want is when a new user is created there email gets added to the list of emails for the newsletter.

**Comment by Cloud9Developer** [comment]
I believe I have a feature request in the backlog that would pull in usernames (in email format, if they match email format).
